version: 2.1
description: This is an inline job

orbs:
  monorepo:
    commands:
      should_be_run:
        parameters:
          path:
            type: string
        steps:
          - run: echo "hello <<parameters.path>>, from the inline command"


jobs:
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - monorepo/should_be_run:
          path: test, test2

workflows:
  build-test-deploy:
    jobs:
      - test
