jobs:
  build:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - run:
          name: Do something
          command: 'echo something'
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
            branches:
              ignore: /.*/
